### ISSUE TITLE
Modbus Server Implementation

### ISSUE THREAD

**Issue by idahogray** [samuelventura/modbus#1]
I am working on a Modbus Server implementation and I thought you might be interested. I am just learning Elixir and this is my first project. I have function codes 1, 2, 3, 4, 5, 6, 15, and 16 implemented. I have a TCP server developed and my last step will be to link the TCP portion with the modbus portion. I don't want to put an exact completion date on it but I will say my goal is "soon".

It is fully tested but the documentation is non-existent at this point. I also have not done any releases on hex.

[Modbus Server](https://bitbucket.org/idahogray/modbus-elixir)

**Comment by idahogray** [comment]
I made made some progress on the Modbus Server implementation noted above. The documentation has improved greatly and I have the TCP portion of it working now. Still no releases on hex because I want to add some more tests.

**Comment by samuelventura** [comment]
Thank you for sharing. Will take a look at it!

Notice that [modbus](https://github.com/samuelventura/modbus) has now the capability to act both as master and slave but at the library level. No standalone installer is provided or planned.
