### ISSUE TITLE
Float Values

### ISSUE THREAD

**Issue by gallexme** [samuelventura/modbus#2]
Hey Very nice Library,
i would like to know how i can get 32 bit float values which were split into 2 registers
for example i get these values: [12594,42381] which should be something like -2.449
any idea?
maybe it would be a good idea to add it as public helpers functions inside your library

**Comment by gallexme** [comment]
Got it working you may can add it to the docs:
basically when u have split the float32bit into 2 16bit registers
and you read them with :rhi or something
assmume result are your 2 register values
 lsb =  Enum.at(result, 0)
msb = Enum.at(result, 1)
<<num::float-32>> = << msb::16,lsb::16,>>
num is then the float value of it

**Comment by samuelventura** [comment]
Actually I needed that feature long ago but had delayed its implementation. The readme code sample includes writing/reading to opto22 analog channels which are IEEE754 encoded. Same sample is found at script/opto22.exs. Check that both have been updated to use the helper you suggested.

BTW. For RTU check [baud](https://github.com/samuelventura/baud) which relays on modbus for the crc wrapping and on [sniff](https://github.com/samuelventura/sniff) for the serial transport.
