### ISSUE TITLE
Matcherror

### ISSUE THREAD

**Issue by gallexme** [samuelventura/modbus#3]
Hello,
for example: when i read from register 32 to 38
i get correct values:
rawdata:
<<0, 0, 0, 0, 0, 15, 1, 4, 12, 0, 0, 0, 0, 64, 64, 0, 0, 64, 64, 0, 0>>
data: [0, 0, 16448, 0, 16448, 0]
but when i read 34-38
i get a match error
Raw Data:
<<0, 0, 0, 0, 0, 3, 1, 132, 2, 34, 0, 4, 0, 64, 64, 0, 0>>

11:31:19.429 [error] GenServer #PID<0.185.0> terminating
** (MatchError) no match of right hand side value: 11
    (modbus) lib/tcp.ex:37: Modbus.Tcp.unwrap/2
    (modbus) lib/tcp.ex:20: Modbus.Tcp.parse_res/3
    (modbus) lib/master.ex:116: anonymous fn/3 in Modbus.Tcp.Master.exec/3
    (elixir) lib/agent/server.ex:16: Agent.Server.handle_call/3
    (stdlib) gen_server.erl:615: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:647: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:get_and_update, #Function<0.7545526/1 in Modbus.Tcp.Master.exec/3>}
State: {#Port<0.7900>, 0}

BTW: Im reading the data from an Acromag Device

**Comment by samuelventura** [comment]
Please share the exact code to test it against some other device.

**Comment by samuelventura** [comment]
Found the problem:

- First case the reported and actual data length match <<0, 0, 0, 0, 0, 15, 1, 4, 12, 0, 0, 0, 0, 64, 64, 0, 0, 64, 64, 0, 0>>.
  - 0, 0, 0, 0, 0, 15 is the header reporting that 15 more bytes are coming next
  - 1, 4, 12, 0, 0, 0, 0, 64, 64, 0, 0, 64, 64, 0, 0 is the data and contains exactly 15 bytes
- Second response reports a length of 3 (0, 0, 0, 0, 0, 3) but its data is much larger (1, 132, 2, 34, 0, 4, 0, 64, 64, 0, 0) with a total of 11 bytes.

I think your Acromag Device has a faulty TCP modbus layer. I have seen that for other devices where querying for either each point or all at once works but querying an slice of them fails.

```elixir
iex(2)> Modbus.Tcp.unwrap <<0, 0, 0, 0, 0, 15, 1, 4, 12, 0, 0, 0, 0, 64, 64, 0, 0, 64, 64, 0, 0>>
{<<1, 4, 12, 0, 0, 0, 0, 64, 64, 0, 0, 64, 64, 0, 0>>, 0}
iex(3)> Modbus.Tcp.unwrap <<0, 0, 0, 0, 0, 3, 1, 132, 2, 34, 0, 4, 0, 64, 64, 0, 0>>             
** (MatchError) no match of right hand side value: 11
    (modbus) lib/tcp.ex:42: Modbus.Tcp.unwrap/1
```
