### ISSUE TITLE
Inconsistent behavior between errors on connect, vs errors after connected

### ISSUE THREAD

**Issue by naveedkakal** [samuelventura/modbus#6]
Hi - unsure if this is an 'issue' or a design choice, but I wanted to ask about it.

https://github.com/samuelventura/modbus/blob/master/lib/master.ex#L131

In the establishing of the connection, if the `:gen_tcp.connect/4` returns an error during initial connection, the library genserver returns a `{:stop, reason}` instead of an `{:error, reason}`, but a tcp error after connection, returns an `{:error, reason}` tuple

For me this lead to me having to trap exits  for the initial connection errors, which didn't feel great.

Thanks for the library, has worked well for me and really appreciate the reduced logging noise and handling of the txn id rollver, i had some gross code to try and swap in a new connection when the txn id got above 64000

Cheers

**Comment by samuelventura** [comment]
What I understand form your request is that you expect `Master` to honor the error handling standard without any unexpected signal/exception. I am not sure how to accomplish that with a GenServer other than having the transport connection performed at `Master.start_link` which has a smell because I would expect all IO to run within the server process, or adding a post init explicit transport connection call to be able to return `{:error, reason}` without having the server process killed automatically. Returning anything other then `{:ok, state}` from `Server.init` will generate the exit signal to the parent you are trying to prevent. It is also outside the scope of this module to ignore the connection failure and try to reconnect later on. 

We are currently using this from a supervised process tree that follows the let it crash principle but I clearly see that a sudden exit signal is not always easy to integrate and feels totally out of place from the iex shell.

Because of TxID, anything outside a `GenServer` would need to handle the state update that would follow any exec. That discouraged me in the past because holding an opaque unchanging pid is easier. It would be something like:

```elixir
alias Modbus.Master.Connection
{:ok, conn} = Connection.open(opts)
#must carry conn returned from one exec to the next
{conn, result} = Connection.exec(conn, cmd1, timeout)
{conn, result} = Connection.exec(conn, cmd2, timeout)
{conn, result} = Connection.exec(conn, cmd3, timeout)
...
Connection.close(conn)
```

I just pushed a new `Modbus.Master.Connection` module (no docs). Could you help me confirm it behaves in the totally predictable way your are expecting?

```elixir
Interactive Elixir (1.13.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(5)> {:ok, conn} = Modbus.Master.Connection.open ip: {10,77,0,10}, port: 502, timeout: 2000 
{:ok,
 %{
   proto: Modbus.Tcp.Protocol,
   tid: 0,
   trans: {Modbus.Tcp.Transport, #Port<0.8>}
 }}
iex(6)> {conn, res} = Modbus.Master.Connection.exec conn, {:fc, 1, 4, 1}                      
{%{
   proto: Modbus.Tcp.Protocol,
   tid: 1,
   trans: {Modbus.Tcp.Transport, #Port<0.8>}
 }, :ok}
iex(7)> {conn, res} = Modbus.Master.Connection.exec conn, {:fc, 1, 4, 0}                      
{%{
   proto: Modbus.Tcp.Protocol,
   tid: 2,
   trans: {Modbus.Tcp.Transport, #Port<0.8>}
 }, :ok}
iex(8)> Modbus.Master.Connection.close conn                                                   
:ok
...
iex(9)> Modbus.Master.Connection.open ip: {10,77,0,10}, port: 5020, timeout: 2000              
{:error, :econnrefused}
```

As you can see the exposed state is not hidded by the process pid this time, but on the other hand a connection failure won't crash the shell process.

**Comment by naveedkakal** [comment]
Thank you for your prompt reply!

Digesting a bit the changes with the `Connection` module.  I see the challenges if start_link needs `{:ok, state}` to successfully launch.  In that sense, the old behavior of always returning the {:ok, pid} regardless of if the connection maybe is the better approach?

The version just before this `Connection` module is actually working well for me, I just had to learn a bit about trapping exits and was concerned that I was aggressively trapping.

Here is my client module I have been shaping up - this question about the start_link error behavior spawned due to the trapping of the exits you'll see below.  This app's purpose is just to provide read/write access via an API as several other apps talk to the same controller, and the controller does not play nice with unbounded incoming connections.  

I am newer to elixir so if you have any suggestions or if something looks really off here please let me know!

```elixir 
# Modeled off of this great article https://andrealeopardi.com/posts/connection-managers-with-gen_statem/
# A persistent process to keep a modbus tcp connection
# available for read/write usage.
defmodule PlcInterface.ModbusClient do
  use GenStateMachine

  require Logger
  alias PlcInterface.ModbusAdapter

  @heartbeat_time 2000
  @reconnect_time 2000

  # Client

  def start_link(opts \\ []) do
    GenStateMachine.start_link(__MODULE__, opts, name: __MODULE__)
  end

  def init(_opts) do
    Process.flag(:trap_exit, true)

    data = %{last_request: Timex.now()}

    actions = [
      {:next_event, :internal, :connect},
      {{:timeout, :heartbeat}, @heartbeat_time, nil}
    ]

    {:ok, :disconnected, data, actions}
  end

  def state() do
    GenStateMachine.call(__MODULE__, :get_state)
  end

  def read(address, length) do
    GenStateMachine.call(__MODULE__, {:read, address, length})
  end

  def write(address, values) do
    GenStateMachine.call(__MODULE__, {:write, address, values})
  end

  # Server (callbacks)

  def handle_event(:internal, :connect, :disconnected, data) do
    case ModbusAdapter.connect() do
      {:ok, pid} ->
        Logger.info("Modbus Connection Established!")
        {:next_state, {:connected, pid}, data}

      _ ->
        Logger.error("Modbus Connection Failed!")
        {:next_state, :disconnected, data, [{{:timeout, :reconnect}, @reconnect_time, nil}]}
    end
  end

  def handle_event({:timeout, :reconnect}, _content, _state, _data) do
    actions = [{:next_event, :internal, :connect}]
    {:keep_state_and_data, actions}
  end

  def handle_event({:timeout, :heartbeat}, _, {:connected, pid}, data) do
    if Timex.diff(Timex.now(), data.last_request, :seconds) > 3 do
      case ModbusAdapter.read(pid, 3001, 1) do
        {:ok, _data} ->
          {:keep_state, %{data | last_request: Timex.now()},
           [{{:timeout, :heartbeat}, @heartbeat_time, nil}]}

        {:error, _reason} ->
          Process.unlink(pid)
          Modbus.Master.stop(pid)

          actions = [
            {{:timeout, :heartbeat}, @heartbeat_time, nil},
            {:next_event, :internal, :connect}
          ]

          {:next_state, :disconnected, data, actions}
      end
    else
      {:keep_state_and_data, [{{:timeout, :heartbeat}, @heartbeat_time, nil}]}
    end
  end

  def handle_event({:timeout, :heartbeat}, _content, _state, _data) do
    {:keep_state_and_data, [{{:timeout, :heartbeat}, @heartbeat_time, nil}]}
  end

  def handle_event({:call, from}, {:read, address, length}, {:connected, pid}, data) do
    case ModbusAdapter.read(pid, address, length) do
      {:ok, values} ->
        {:keep_state, %{data | last_request: Timex.now()}, [{:reply, from, {:ok, values}}]}

      {:error, reason} ->

        Process.unlink(pid)
        Modbus.Master.stop(pid)

        actions = [
          {:reply, from, {:error, reason}},
          {:next_event, :internal, :connect}
        ]

        {:next_state, :disconnected, data, actions}
    end
  end

  def handle_event({:call, from}, {:read, _address, _length}, _state, _data) do
    {:keep_state_and_data, [{:reply, from, {:error, :disconnected}}]}
  end

  def handle_event({:call, from}, {:write, address, values}, {:connected, pid}, data) do
    case ModbusAdapter.write(pid, address, values) do
      :ok ->
        {:keep_state, %{data | last_request: Timex.now()}, [{:reply, from, :ok}]}

      {:error, reason} ->
        actions = [
          {:reply, from, {:error, reason}},
          {:next_event, :internal, :connect}
        ]

        {:next_state, :disconnected, data, actions}
    end
  end

  def handle_event({:call, from}, {:write, _address, _values}, _state, _data) do
    {:keep_state_and_data, [{:reply, from, {:error, :disconnected}}]}
  end

  def handle_event({:call, from}, :get_state, state, data) do
    {:next_state, state, data, [{:reply, from, {state, data}}]}
  end

  # these traps here to catch errors on making the connection
  # If we get trap an econnrefused exit, we'd prefer to manage our own reconnection
  def handle_event(:info, {:EXIT, _pid, :econnrefused}, _state, data) do
    {:next_state, :disconnected, data, [{{:timeout, :reconnect}, @reconnect_time, nil}]}
  end

  def handle_event(:info, {:EXIT, _pid, :timeout}, _state, data) do
    {:next_state, :disconnected, data, [{{:timeout, :reconnect}, @reconnect_time, nil}]}
  end

  def handle_event(event_type, event_content, state, data) do
    # Call the default implementation from GenStateMachine
    super(event_type, event_content, state, data)
  end
end
```

I extracted some of the specifics to a separate module which is below

```elixir
# extracted some of our specific needs to here to help separate
# the interaction with the modbus library from general connection management
defmodule PlcInterface.ModbusAdapter do
  def connect() do
    case Modbus.Master.start_link(ip: PlcInterface.plc_ip(), port: 502) do
      {:ok, pid} ->
        {:ok, pid}

      {:error, reason} ->
        {:error, reason}
    end
  end

  def stop(pid), do: Modbus.Master.stop(pid)

  def read(pid, address, length) do
    max = address + length

    Range.new(address, address + length, 127)
    |> Enum.reduce({:ok, []}, fn chunk_start, {status, vals} ->
      case status do
        :ok ->
          chunk_end = Enum.min([max, chunk_start + 127])

          case Modbus.Master.exec(pid, {:rhr, 1, chunk_start, chunk_end - chunk_start}) do
            {:ok, chunk_vals} ->
              {:ok, vals ++ chunk_vals}

            {:error, reason} ->
              {:error, reason}
          end

        _ ->
          {status, vals}
      end
    end)
  end

  def write(pid, address, values) do
    values
    |> Enum.chunk_every(127)
    |> Enum.with_index(0)
    |> Enum.map(fn {vals, i} -> {address + i * 127, vals} end)
    |> Enum.reduce(:ok, fn {addy, vals}, acc ->
      case acc do
        :ok ->
          Modbus.Master.exec(pid, {:phr, 1, addy, vals})

        _ ->
          acc
      end
    end)
  end
end

```

**Comment by samuelventura** [comment]
Keeping a process alive is basically implementing a specialized supervisor and that will require trapping exits at some point. You can use the new `Modbus.Master.Connection` to avoid trapping exits and avoid unlinking before stopping. This new module is passive and runs in the caller process. You have to carry the state though. Notice that the state to carry is not a pid anymore.

`Modbus.Master` now relies on `Modbus.Master.Connection` but it should be totally transparent to you.

Unfortunatelly, this split is as far as I can get for now. Having a reconnecting master is in the mental todo but not having the test bed for it nor the need would cripple my ability to get the use case right. I think you are better positioned to make that contribution at this moment.

**Comment by naveedkakal** [comment]
I think reconnection behavior being left to the consumer is a fine design choice, not all industrial controllers are modern and the quirks that come with specific vendors and implementations are quite broad.

Appreciate the work on this library and this discussion thank you!
